remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Поиск геометрических пересечений
description: Поиск геометрических пересечений между элементами 3D-моделей **Топоматик 360**.